version: '3.8'

services:
  threeb-website:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: threeb-website
    
    # Variables d'environnement
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"